#!/usr/bin/env -S uv run --script --native-tls
# /// script
# requires-python = ">=3.10"
# version = "0.1"
# dependencies = [
#     "pyinfra",
# ]
# ///

import subprocess
from pathlib import Path

conf_path = Path("for-bind")
if not conf_path.exists():
	exit(f'Could not find {str(conf_path)}". Exiting.')

# List of paths in conf_path; these are the names that make up the inventory of servers
inv_paths = []
server_names = []
for this_thing in conf_path.glob("*"):
	if this_thing.is_dir():
		inv_paths.append(this_thing)
		server_names.append(str(this_thing.name))

inv_path = conf_path / "inventory.py"
with inv_path.open(mode="wt") as f:
	f.write(f'server_hosts = ({sorted(server_names)}, ' + '{"ssh_user": "root", "myvar": "one"})\n')

opts_path = conf_path / "operations.py"  # Must end in .py to work with pyinfra

opts_contents = f'source_dir = "{str(conf_path)}"\n'
opts_contents += """
from pyinfra import host
from pyinfra.operations import files, server, apt, git
from pyinfra.facts.files import File, FindDirectories

regular_user = "user1"
regular_user_home = f"/home/{regular_user}"
server.user(name="Add non-root user", user=regular_user, present=True, home=regular_user_home, shell="/bin/bash")

files.sync(name="Move files to the conf", src=f'{source_dir}/'+host.name, dest="/root/conf", delete=True)

if host.get_fact(File, "/root/k/var/run/bind/bind.pid"):
	server.shell(name="Stop the server", commands=["kill `cat /root/k/var/run/bind/bind.pid`"])

rebuild_canary = "/root/rebuild-canary"
bind_git_dir = "/root/bind9"
bind_target_dir = "/root/b"
################ packages_for_bind = "git libtool autoconf automake make pkg-config liburcu-dev libgnutls28-dev libedit-dev liblmdb-dev libcap-ng-dev libsystemd-dev libidn2-dev libprotobuf-c-dev protobuf-c-compiler protobuf-compiler libfstrm-dev libmaxminddb-dev libnghttp2-dev libbpf-dev libxdp-dev libmnl-dev python3-sphinx python3-sphinx-panels softhsm2".split(" ")
################### bind_making_commands = f"cd /root/knot-dns && git checkout deleg_experimental && autoreconf -if && ./configure --prefix={knot_target_dir} && make && make install &&  ldconfig"

if host.get_fact(File, rebuild_canary):
	apt.packages(name="Do the apt", update=True, packages=packages_for_bind)
	files.directory(name="Remove {bind_git_dir}", path=bind_git_dir, present=False, force=True)
	files.directory(name=f"Remove {bind_target_dir}", path=bind_target_dir, present=False, force=True)
	files.directory(name="Add {bind_git_dir}", path=bind_git_dir, present=True, force=True)
	files.directory(name=f"Add {bind_target_dir}", path=bind_target_dir, present=True, force=True)
	############ git.repo(name="Do the git pull", src="https://gitlab.nic.cz/knot/knot-dns.git", dest=knot_git_dir, branch="deleg_experimental")
	server.shell(name="Make latest BIND", commands=bind_making_commands)
	files.file(path=rebuild_canary, present=False)

##### server.shell(name="Start the server", commands=["/root/k/sbin/knotd -c /root/conf/knot.conf -v -d"])
"""

with opts_path.open(mode="wt") as f:
	f.write(opts_contents)

the_infra_cmd = f'pyinfra -y {str(inv_path)} {str(opts_path)}'
print(the_infra_cmd)
subprocess.run(the_infra_cmd, shell=True)

###############################################################

from pyinfra import host
from pyinfra.operations import files, server, apt, git
from pyinfra.facts.files import File, FindDirectories
import os

regular_user = "user1"
regular_user_home = f"/home/{regular_user}"
server.user(name="Add non-root user", user=regular_user, present=True, home=regular_user_home, shell="/bin/bash")

if os.path.exists("to_move"):
	files.sync(name="Move files to the non-root user", src="to_move", dest=f"/home/{regular_user}/", user=regular_user, delete=True)

rebuild_canary = f"/{regular_user_home}/rebuild-canary"

knot_git_dir = f"{regular_user_home}/knot-dns"
knot_target_dir = f"{regular_user_home}/k"
packages_for_knot = "git libtool autoconf automake make pkg-config liburcu-dev libgnutls28-dev libedit-dev liblmdb-dev libcap-ng-dev libsystemd-dev libidn2-dev libprotobuf-c-dev protobuf-c-compiler protobuf-compiler libfstrm-dev libmaxminddb-dev libnghttp2-dev libbpf-dev libxdp-dev libmnl-dev python3-sphinx python3-sphinx-panels softhsm2".split(" ")
knot_making_commands = f"cd {knot_git_dir} && git checkout deleg_experimental && autoreconf -if && ./configure --prefix={knot_target_dir} && make && make install"

# https://gitlab.isc.org/isc-projects/bind9.git
bind_git_dir = f"{regular_user_home}/bind-dns"
bind_target_dir = f"{regular_user_home}/b"
packages_for_bind = "build-essential git curl meson pkgconf libuv1-dev liblmdb-dev liburcu-dev libcap-dev libjemalloc-dev libcrypto++-dev libssl-dev libuv1-dev".split(" ")
bind_making_commands = f"cd {bind_git_dir} && git checkout each-deleg-auth && meson setup build-dir && meson compile -C build-dir && cd build-dir && meson install --destdir {bind_target_dir}"

if host.get_fact(File, rebuild_canary):
	# Bind
	apt.packages(name="Check the apt for BIND", update=True, packages=packages_for_bind)
	files.directory(name=f"Remove {bind_git_dir}", path=bind_git_dir, present=False, force=True,  _su_user=regular_user)
	files.directory(name=f"Remove {bind_target_dir}", path=bind_target_dir, present=False, force=True,  _su_user=regular_user)
	# git.repo(name="Do the git clone", src="https://gitlab.isc.org/isc-projects/bind9.git", dest=bind_git_dir, branch="each-deleg-auth", _su_user=regular_user)
	server.shell(name="Do the git clone", commands=f"git clone --single-branch --branch each-deleg-auth https://gitlab.isc.org/isc-projects/bind9.git {bind_git_dir}", _su_user=regular_user)
	server.shell(name="Make latest bind", commands=bind_making_commands,  _su_user=regular_user)
	arch_names = host.get_fact(FindDirectories, f"{bind_target_dir}/usr/local/lib/", maxdepth=1)
	if len(arch_names) == 2:
		this_arch = arch_names[1]
		server.shell(name="ldconfig", commands=[f"ldconfig {this_arch}"])
	else:
		print(f"Found {arch_names} which has more or less than two elements. Not doing the ldconfig.")
	##### files.file(path=rebuild_canary, present=False)
