#!/usr/bin/env -S uv run --script --native-tls
# /// script
# requires-python = ">=3.10"
# version = "0.1"
# dependencies = [
#     "pyinfra",
# ]
# ///

import subprocess
from pathlib import Path

conf_path = Path("for-knot")
if not conf_path.exists():
	exit(f'Could not find {str(conf_path)}". Exiting.')

# List of paths in conf_path; these are the names that make up the inventory of servers
inv_paths = []
server_names = []
for this_thing in conf_path.glob("*"):
	if this_thing.is_dir():
		inv_paths.append(this_thing)
		server_names.append(str(this_thing.name))

inv_path = conf_path / "inventory.py"
with inv_path.open(mode="wt") as f:
	f.write(f'server_hosts = ({sorted(server_names)})\n')

opts_path = conf_path / "operations.py"  # Must end in .py to work with pyinfra

opts_contents = f'source_dir = "{str(conf_path)}"\n'
opts_contents += """
from pyinfra import host
from pyinfra.operations import files, server, apt, git
from pyinfra.facts.files import File

files.sync(name="Move files to the conf", src=f'{source_dir}/'+host.name, dest="/root/conf", delete=True)

if host.get_fact(File, "/root/k/var/run/knot/knot.pid"):
	server.shell(name="Stop the server", commands=["kill `cat /root/k/var/run/knot/knot.pid`"])

rebuild_canary = "/root/rebuild-canary"
knot_git_dir = "/root/knot-dns"
knot_target_dir = "/root/k"
packages_for_knot = "git libtool autoconf automake make pkg-config liburcu-dev libgnutls28-dev libedit-dev liblmdb-dev libcap-ng-dev libsystemd-dev libidn2-dev libprotobuf-c-dev protobuf-c-compiler protobuf-compiler libfstrm-dev libmaxminddb-dev libnghttp2-dev libbpf-dev libxdp-dev libmnl-dev python3-sphinx python3-sphinx-panels softhsm2".split(" ")
knot_making_commands = f"cd /root/knot-dns && git checkout deleg_experimental && autoreconf -if && ./configure --prefix={knot_target_dir} && make && make install &&  ldconfig"

if host.get_fact(File, rebuild_canary):
	apt.packages(name="Do the apt", update=True, packages=packages_for_knot)
	files.directory(name="Remove {knot_git_dir}", path=knot_git_dir, present=False, force=True)
	files.directory(name=f"Remove {knot_target_dir}", path=knot_target_dir, present=False, force=True)
	files.directory(name="Add {knot_git_dir}", path=knot_git_dir, present=True, force=True)
	files.directory(name=f"Add {knot_target_dir}", path=knot_target_dir, present=True, force=True)
	git.repo(name="Do the git pull", src="https://gitlab.nic.cz/knot/knot-dns.git", dest=knot_git_dir, branch="deleg_experimental")
	server.shell(name="Make latest Knot", commands=knot_making_commands)
	files.file(path=rebuild_canary, present=False)

server.shell(name="Start the server", commands=["/root/k/sbin/knotd -c /root/conf/knot.conf -v -d"])
"""

with opts_path.open(mode="wt") as f:
	f.write(opts_contents)

the_infra_cmd = f'pyinfra -y --ssh-user=root {str(inv_path)} {str(opts_path)}'
print(the_infra_cmd)
subprocess.run(the_infra_cmd, shell=True)
